name: build-docs

on: 
  push:
    branches:
    - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install -g bootprint
      - run: npm install -g bootprint-openapi
      - run: bootprint openapi http://petstore.swagger.io/v2/swagger.json target
      - run: ls
      - name: push docs html
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: docs
          FOLDER: target
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Coverage: ({sha}) {msg}"
